# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f67b18f1c82b63657679a6cd9547574b8dc7362a79bfb6e01202ad9c4aa1a153ff535003d1d9db4aa83e902b75cd970949f4928da3c862122f374802e1dee6a4

test:
  secret_key_base: 946aefaf7414827165fb5666d9db9a56bbcda258b6eb007659c2d8667709c76485e2b764f3cc577ff9707bb131ca491c5e86321583fa1f4c4f5f64082c25a3cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
